In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("Customer (1).csv")

In [3]:
df

,Customer ID,Customer Name,Segment,Age,Country,City,State,Postal Code,Region
0,CG-12520,Claire Gute,Consumer,67,United States,Henderson,Kentucky,42420,South
1,DV-13045,Darrin Van Huff,Corporate,31,United States,Los Angeles,California,90036,West
2,SO-20335,Sean O'Donnell,Consumer,65,United States,Fort Lauderdale,Florida,33311,South
3,BH-11710,Brosina Hoffman,Consumer,20,United States,Los Angeles,California,90032,West
4,AA-10480,Andrew Allen,Consumer,50,United States,Concord,North Carolina,28027,South
...,...,...,...,...,...,...,...,...,...
788,CJ-11875,Carl Jackson,Corporate,64,United States,Philadelphia,Pennsylvania,19140,East
789,RS-19870,Roy Skaria,Home Office,39,United States,Burlington,Iowa,52601,Central
790,SC-20845,Sung Chung,Consumer,69,United States,Arlington Heights,Illinois,60004,Central
791,RE-19405,Ricardo Emerson,Consumer,35,United States,Kent,Ohio,44240,East
792,SM-20905,Susan MacKendrick,Consumer,46,United States,Newark,Ohio,43055,East

In [4]:
df.info

<bound method DataFrame.info of     Customer ID      Customer Name      Segment  Age        Country  \
0      CG-12520        Claire Gute     Consumer   67  United States
1      DV-13045    Darrin Van Huff    Corporate   31  United States
2      SO-20335     Sean O'Donnell     Consumer   65  United States
3      BH-11710    Brosina Hoffman     Consumer   20  United States
4      AA-10480       Andrew Allen     Consumer   50  United States
..          ...                ...          ...  ...            ...
788    CJ-11875       Carl Jackson    Corporate   64  United States
789    RS-19870         Roy Skaria  Home Office   39  United States
790    SC-20845         Sung Chung     Consumer   69  United States
791    RE-19405    Ricardo Emerson     Consumer   35  United States
792    SM-20905  Susan MacKendrick     Consumer   46  United States

                  City           State  Postal Code   Region
0            Henderson        Kentucky        42420    South
1          Los Angeles      California        90036     West
2      Fort Lauderdale         Florida        33311    South
3          Los Angeles      California        90032     West
4              Concord  North Carolina        28027    South
..                 ...             ...          ...      ...
788       Philadelphia    Pennsylvania        19140     East
789         Burlington            Iowa        52601  Central
790  Arlington Heights        Illinois        60004  Central
791               Kent            Ohio        44240     East
792             Newark            Ohio        43055     East

[793 rows x 9 columns]>

In [5]:
df.isnull().sum()

Customer ID      0
Customer Name    0
Segment          0
Age              0
Country          0
City             0
State            0
Postal Code      0
Region           0
dtype: int64

In [6]:
df.shape

(793, 9)

In [7]:
df.head

<bound method NDFrame.head of     Customer ID      Customer Name      Segment  Age        Country  \
0      CG-12520        Claire Gute     Consumer   67  United States
1      DV-13045    Darrin Van Huff    Corporate   31  United States
2      SO-20335     Sean O'Donnell     Consumer   65  United States
3      BH-11710    Brosina Hoffman     Consumer   20  United States
4      AA-10480       Andrew Allen     Consumer   50  United States
..          ...                ...          ...  ...            ...
788    CJ-11875       Carl Jackson    Corporate   64  United States
789    RS-19870         Roy Skaria  Home Office   39  United States
790    SC-20845         Sung Chung     Consumer   69  United States
791    RE-19405    Ricardo Emerson     Consumer   35  United States
792    SM-20905  Susan MacKendrick     Consumer   46  United States

                  City           State  Postal Code   Region
0            Henderson        Kentucky        42420    South
1          Los Angeles      California        90036     West
2      Fort Lauderdale         Florida        33311    South
3          Los Angeles      California        90032     West
4              Concord  North Carolina        28027    South
..                 ...             ...          ...      ...
788       Philadelphia    Pennsylvania        19140     East
789         Burlington            Iowa        52601  Central
790  Arlington Heights        Illinois        60004  Central
791               Kent            Ohio        44240     East
792             Newark            Ohio        43055     East

[793 rows x 9 columns]>

In [8]:
X = df.drop(columns=["Segment","Age","Country"])
y = df['Age']

In [9]:
X = pd.get_dummies(X, drop_first=True)

In [10]:
X

,Postal Code,Customer ID_AA-10375,Customer ID_AA-10480,Customer ID_AA-10645,Customer ID_AB-10015,Customer ID_AB-10060,Customer ID_AB-10105,Customer ID_AB-10150,Customer ID_AB-10165,Customer ID_AB-10255,...,State_South Dakota,State_Tennessee,State_Texas,State_Utah,State_Virginia,State_Washington,State_Wisconsin,Region_East,Region_South,Region_West
0,42420,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,90036,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,33311,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,90032,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,28027,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
788,19140,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
789,52601,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
790,60004,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
791,44240,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
792,43055,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [11]:
y

0      67
1      31
2      65
3      20
4      50
       ..
788    64
789    39
790    69
791    35
792    46
Name: Age, Length: 793, dtype: int64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    random_state=42,
    test_size=0.2
)

In [13]:
X_train

,Postal Code,Customer ID_AA-10375,Customer ID_AA-10480,Customer ID_AA-10645,Customer ID_AB-10015,Customer ID_AB-10060,Customer ID_AB-10105,Customer ID_AB-10150,Customer ID_AB-10165,Customer ID_AB-10255,...,State_South Dakota,State_Tennessee,State_Texas,State_Utah,State_Virginia,State_Washington,State_Wisconsin,Region_East,Region_South,Region_West
323,17602,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
362,92563,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
79,90004,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
148,94109,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
694,77095,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,98105,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
106,95051,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
270,19013,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
435,94110,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
102,43017,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [14]:
X_test

,Postal Code,Customer ID_AA-10375,Customer ID_AA-10480,Customer ID_AA-10645,Customer ID_AB-10015,Customer ID_AB-10060,Customer ID_AB-10105,Customer ID_AB-10150,Customer ID_AB-10165,Customer ID_AB-10255,...,State_South Dakota,State_Tennessee,State_Texas,State_Utah,State_Virginia,State_Washington,State_Wisconsin,Region_East,Region_South,Region_West
137,37130,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
198,72701,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
739,61107,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
583,84106,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
655,31907,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
737,78501,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
760,77070,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
541,28205,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
375,19134,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
434,6360,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [15]:
y_test

137    67
198    31
739    55
583    61
655    57
       ..
737    41
760    18
541    47
375    60
434    62
Name: Age, Length: 159, dtype: int64

In [16]:
y_train

323    28
362    39
79     51
148    70
694    55
       ..
71     61
106    60
270    58
435    67
102    25
Name: Age, Length: 634, dtype: int64

In [17]:
model = LinearRegression()

In [18]:
model

LinearRegression()

In [19]:
model.fit(X_train, y_train)

LinearRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([44.53360522, 37.68250089, 39.23003871, 44.31182503, 40.83563478,
       44.53158562, 45.3043251 , 44.19172849, 40.83563478, 36.89707015,
       40.0464372 , 40.19588454, 44.8441582 , 53.5156508 , 54.99878833,
       44.8171373 , 44.53152883, 46.07451042, 41.73776692, 44.84427178,
       51.58704777, 41.25587192, 49.44129185, 40.44977073, 51.30557411,
       49.44129185, 35.20260406, 45.3380485 , 44.81736446, 47.54035965,
       46.67613512, 40.94569302, 48.2853367 , 44.8441582 , 48.28584781,
       35.52457069, 43.81352024, 36.81430899, 41.01127784, 36.44620738,
       44.81726034, 47.540265  , 44.81726034, 44.81726034, 41.74259404,
       40.19600758, 42.50725553, 45.02851024, 45.27118908, 43.68164399,
       45.11354503, 40.04631415, 47.54035965, 41.51791651, 45.30989048,
       54.52287814, 39.5546849 , 44.81711837, 40.04647506, 43.21639829,
       47.54024607, 39.05973128, 51.99740554, 39.75252451, 40.83563478,
       42.2484468 , 47.54035965, 40.0464372 , 44.53158562, 44.84414873,
       49.9572887 , 48.2853367 , 44.81711837, 40.4501857 , 44.10016389,
       37.31561093, 53.10517485, 44.53161402, 40.83563478, 44.53360522,
       47.54035965, 47.54035965, 44.07921894, 40.04635201, 42.00215002,
       47.54035965, 37.79635007, 45.90212556, 42.35294469, 47.54035965,
       43.5793891 , 44.8441582 , 42.73952803, 43.4945927 , 45.12680541,
       40.04635201, 47.54024607, 35.80404236, 47.53391846, 38.71116877,
       43.66249642, 40.046087  , 44.54885409, 44.34169611, 38.71116877,
       40.046087  , 42.35301095, 52.38857936, 50.14436438, 37.1828363 ,
       51.62203532, 45.44828965, 44.84414873, 40.19600758, 45.76380516,
       45.11311911, 44.8171373 , 45.76396606, 50.80235818, 45.11457671,
       36.48311473, 52.0634855 , 42.35294469, 45.56836946, 46.07451042,
       44.84427178, 43.80133179, 45.27118908, 55.63592728, 44.08653849,
       48.28528938, 34.89871541, 47.540265  , 40.83563478, 40.25367966,
       47.54024607, 45.85393214, 44.54678126, 44.53139632, 48.28584781,
       46.91942651, 42.62421396, 47.540265  , 40.04631415, 40.27064084,
       41.8065616 , 50.72959764, 36.3224497 , 45.31543694, 44.40423916,
       47.540265  , 48.28561119, 29.40339774, 40.04631415, 45.79692298,
       48.28561119, 42.2484468 , 44.53152883, 41.33093198])

In [22]:
df.tail(3)

,Customer ID,Customer Name,Segment,Age,Country,City,State,Postal Code,Region
790,SC-20845,Sung Chung,Consumer,69,United States,Arlington Heights,Illinois,60004,Central
791,RE-19405,Ricardo Emerson,Consumer,35,United States,Kent,Ohio,44240,East
792,SM-20905,Susan MacKendrick,Consumer,46,United States,Newark,Ohio,43055,East

In [30]:
test_new = X_test.iloc[[0]]

new_pred = model.predict(test_new)

new_pred

array([44.53360522])

In [31]:
print("completed model linear")

completed model linear