In [1]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("test.csv")

In [3]:
df

      x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
..   ..        ...
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]

In [4]:
df.head

<bound method NDFrame.head of       x          y
0    77  79.775152
1    21  23.177279
2    22  25.609262
3    20  17.857388
4    36  41.849864
..   ..        ...
295  71  68.545888
296  46  47.334876
297  55  54.090637
298  62  63.297171
299  47  52.459467

[300 rows x 2 columns]>

In [5]:
df.isnull().sum()

x    0
y    0
dtype: int64

In [6]:
X = df.iloc[:, 0:1]
y = df.iloc[:, 1]

In [7]:
X

      x
0    77
1    21
2    22
3    20
4    36
..   ..
295  71
296  46
297  55
298  62
299  47

[300 rows x 1 columns]

In [8]:
y

0      79.775152
1      23.177279
2      25.609262
3      17.857388
4      41.849864
         ...
295    68.545888
296    47.334876
297    54.090637
298    63.297171
299    52.459467
Name: y, Length: 300, dtype: float64

In [9]:
X_train, X_test, y_train , y_test = train_test_split(
    X,y,
    train_size=0.2,
    random_state=42,
)

In [10]:
X_test

      x
203  90
266  76
152  94
9     5
233  91
..   ..
14   36
47   68
94   60
263  73
227  87

[240 rows x 1 columns]

In [11]:
X_train

       x
273   72
201   26
161   46
43    76
217   95
145   63
190   92
220    7
251   95
3     20
105   12
53    31
133   25
1     21
131   75
103   74
49    35
80    68
205   13
34    28
91    38
52    52
241   46
13    62
88    59
166   95
294    8
134   28
287   42
243   39
54    59
50    94
174    1
189   46
298   62
187   51
169   35
58    69
48    40
235   74
252   56
21    51
160   42
276   96
191   73
257    6
149    2
130   64
151   32
99    32
87   100
214   23
121   96
299   47
20    89
188   27
71    13
106    1
270   55
102   19

In [12]:
y_train

273     77.996948
201     25.756125
161     46.110211
43      78.042375
217     95.797473
145     63.283124
190     89.731536
220      9.281700
251     90.714817
3       17.857388
105     12.592447
53      31.930635
133     21.322737
1       23.177279
131     74.253628
103     75.692986
49      34.311414
80      70.369875
205     13.121098
34      33.071128
91      38.430764
52      54.081706
241     52.054907
13      61.388007
88      56.824570
166     97.138320
294      5.405221
134     29.317700
287     41.469239
243     36.792248
54      59.612471
50      95.285039
174     -2.761183
189     48.351726
298     63.297171
187     56.430460
169     24.388460
58      70.914643
48      38.147539
235     72.913885
252     61.093678
21      46.913877
160     38.983174
276     94.790817
191     72.862825
257      2.576625
149     -2.819914
130     67.386547
151     29.385050
99      33.384741
87     105.591837
214     23.526472
121     97.274055
299     52.459467
20      92.119063
188     30.494129
71      10.347545
106      0.275307
270     55.816285
102     17.440476
Name: y, dtype: float64

In [13]:
y_test

203    92.887723
266    79.503415
152    97.001484
9       8.746748
233    89.739520
         ...
14     40.247017
47     65.013240
94     60.910543
263    71.003778
227    88.803069
Name: y, Length: 240, dtype: float64

In [14]:
model = RandomForestRegressor(
    random_state=42,
    n_estimators=500,
    max_depth=7
)

model.fit(X_train, y_train)

RandomForestRegressor(max_depth=7, n_estimators=500, random_state=42)

In [15]:
model

RandomForestRegressor(max_depth=7, n_estimators=500, random_state=42)

In [16]:
y_pred = model.predict(X_test)

In [17]:
y_pred

array([ 91.82533352,  76.53137017,  94.98458137,   4.06372909,
        90.9371736 , 102.15009584,  -1.10564277,  -1.05663406,
        12.05337401,  31.28291956,  12.34425574,  65.74861162,
        12.01221918,  35.21787553,  91.62531005, 102.15009584,
        61.97727835,  48.91758938,  29.46061503,  40.38210136,
        53.29260655,  95.78506572,  37.62150501,  21.41882627,
        39.97132885,  51.74245657,  22.9670038 ,  75.60840418,
        91.62531005,   4.06372909,  11.80795543,  52.10106051,
        76.61618784,  95.78506572,  56.606539  ,  -1.05663406,
        94.49080469,  69.77145615,  71.64419242,  53.29260655,
        90.9371736 ,  76.70092053,  12.34425574,  11.48401709,
        71.52671188,  61.97727835,  65.77400387,  11.80795543,
        12.34425574,   4.06372909,  16.88515684,  12.01221918,
        30.79294858,  30.79294858,  56.606539  ,  58.45723528,
        91.82533352,  63.04757429,  76.53137017,  58.45723528,
        91.82533352,  59.4827628 ,  62.56347602,  -1.10564277,
        59.38154432, 102.15009584,  91.82533352,  91.82533352,
        37.40191852,  55.77912639,  91.82533352,  76.53137017,
        35.21787553,  90.9371736 ,  31.01742659,  65.74861162,
        59.38154432,  38.02416157,  38.69511014,  40.38210136,
        12.34425574,  63.04757429,  71.52671188,  38.69511014,
        87.64769596,  67.61206576,  11.48401709,  76.53137017,
        12.05337401,  -1.10564277,  61.97727835,  78.12500438,
        56.606539  ,  95.75334512,  71.52671188,  65.77400387,
        76.26246072,  58.65523046,  58.45723528,  51.74245657,
        11.80795543,  11.48401709,  31.7074748 ,  90.9371736 ,
        18.34748507,  37.40191852,  75.60840418,  91.82533352,
        95.78506572,  21.41882627,  12.01221918,  48.91758938,
        78.12500438,  91.82533352,  31.7074748 ,  16.88515684,
       102.15009584,  38.69511014,  76.26246072,  38.02416157,
        -1.05663406,  55.77912639,  35.21787553,  67.61206576,
        53.29260655,  58.65523046,  30.79294858,  51.30004872,
       102.15009584,  21.41882627,  58.53618731,  94.98458137,
        21.41882627,  91.82533352,  23.12128231,   6.34914069,
        22.65702483,  58.45723528,  48.91758938,  22.65702483,
        23.22738537,   6.34914069,  31.28291956,  65.74861162,
        23.12128231,  12.34425574,  18.34748507,  12.05337401,
        29.2082615 ,  51.32693103,  76.26246072,  91.82533352,
        39.97132885,  31.28291956,  17.97104472,  70.37909733,
        51.32693103,  17.68768522,  17.97104472,  37.40191852,
        41.45152998,   7.38516353,  95.75334512,  51.30004872,
        91.62531005,  74.21589809,  58.53618731,  65.77400387,
        76.61618784,  91.82533352,  11.80795543,  69.77145615,
        91.82533352,  75.60840418,  40.38210136,  41.45152998,
        65.77400387,  76.53137017,  -1.05663406,  95.78506572,
        76.53137017,  76.53137017,  56.606539  ,  59.38154432,
        -1.9295017 ,  30.18474701,  76.53137017,  35.21787553,
        74.21589809,  53.29260655,  76.26246072,  58.65523046,
        59.38154432,  74.23814127,  55.77912639,  17.97104472,
        48.91758938,  29.41146144,  21.41882627,  -1.10564277,
        30.18474701,  96.90646872,  31.28291956,  67.61206576,
        55.77912639,  74.4263255 ,  17.97104472,  65.74861162,
        76.53137017,  31.60783632,  91.82533352,  91.46272571,
        18.34748507,  48.91758938,  59.4827628 ,  78.12500438,
        -1.10564277,  23.12128231,  76.70092053,  90.9371736 ,
        12.01221918,   4.44208527,  56.606539  ,  87.64769596,
        29.2082615 , 102.15009584,  38.69511014,  29.2082615 ,
        76.53137017,  58.53618731,  31.28291956,  91.46272571,
        12.01221918,  69.77145615,  59.4827628 ,  30.18474701,
        70.37909733,  58.65523046,  74.21589809,  91.82533352])

In [24]:
from sklearn.metrics import r2_score

print(r2_score(y_test, y_pred))

0.9794574708225922

In [25]:
y_pred = model.predict(X_test)

accuracy = np.mean(np.abs(y_pred - y_test) / y_test < 0.10) * 100

print("Accuracy:", accuracy, "%")

Accuracy: 67.5 %